Repository meetgom/2024-meetgom-frontend, pull requests merged in 2025-03, with the labels that each got.

#55 Feat/attach eventsheet api
  app/event/new/Step3.tsx
  app/event/new/Step4.tsx
  app/event/new/page.tsx
  app/layout.tsx
  components/DaySelectBox/DaySelectBox.tsx
  components/PinInput/PinInput.tsx
  hooks/queries/eventSheet.ts
  store/eventState.ts
Labels: ✨ Feature

#59 Zustand 리팩토링
  app/ClientProviders.tsx
  app/event/new/Step1.tsx
  app/event/new/Step2.tsx
  app/event/new/Step3.tsx
  app/event/new/Step4.tsx
  app/event/new/page.tsx
  app/layout.tsx
  components/Button/Button.tsx
  components/DatePicker/DatePicker.tsx
  components/DaySelectBox/DaySelectBox.tsx
  components/SelectBox/SelectBox.tsx
  components/TimeRangeBox/TimeRangeBox.tsx
  package-lock.json
  package.json
  store/eventState.ts
  store/useEventStore.ts
  styles/globals.css
  types/Time.ts
  types/eventSheet.ts
  utils/timeUtils.ts
Labels: ⚙️ Setting, 🔨 Refactor, 🎨 Design, 📫 API

#60 fix: useEvent 훅 삭제 및 prettier 버전 업
  hooks/useEvent.ts
  package-lock.json
  package.json
Labels: 🔨 Refactor
